package graficos;

import modelo.Palabra;
import modelo.PalabrasTableModel;
import persistencia.GestorPalabrasXML;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.List;
import controlador.ControladorPrincipal;

public class JFAdmin extends javax.swing.JFrame {

    private ControladorPrincipal controlador;
    private GestorPalabrasXML gestorPalabras;
    private PalabrasTableModel modeloTabla = new PalabrasTableModel();
    private boolean modoEdicion;
    private int filaSeleccionada;

    public JFAdmin() {
        initComponents();
        inicializarComponentes();
    }

    public void inicializarComponentes() {
        this.modoEdicion = false;
        this.filaSeleccionada = -1;
        inicializarGestorPalabras();
        habilitarPanelGestion(false);
    }

    /**
     * Establece el controlador principal
     *
     * @param controlador controlador principal de la aplicación
     */
    public void setControlador(ControladorPrincipal controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panPalabras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPalabras = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        panGestionar = new javax.swing.JPanel();
        txtPalabra = new javax.swing.JTextField();
        lblPalabras = new javax.swing.JLabel();
        lblPistas = new javax.swing.JLabel();
        txtPistas = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PANEL DE ADMINISTRADOR");

        panPalabras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PALABRAS EXISTENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        tblPalabras.setModel(this.modeloTabla);
        jScrollPane1.setViewportView(tblPalabras);

        btnActualizar.setBackground(new java.awt.Color(128, 128, 128));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 165, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPalabrasLayout = new javax.swing.GroupLayout(panPalabras);
        panPalabras.setLayout(panPalabrasLayout);
        panPalabrasLayout.setHorizontalGroup(
            panPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPalabrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPalabrasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)))
                .addContainerGap())
        );
        panPalabrasLayout.setVerticalGroup(
            panPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPalabrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        panGestionar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTIONAR PALABRA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        lblPalabras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPalabras.setText("Palabra:");

        lblPistas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPistas.setText("Pistas:");

        btnCancelar.setBackground(new java.awt.Color(218, 21, 60));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(74, 173, 127));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGestionarLayout = new javax.swing.GroupLayout(panGestionar);
        panGestionar.setLayout(panGestionarLayout);
        panGestionarLayout.setHorizontalGroup(
            panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGestionarLayout.createSequentialGroup()
                .addGroup(panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGestionarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPalabras)
                            .addComponent(lblPistas))
                        .addGap(18, 18, 18)
                        .addGroup(panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPistas)
                            .addComponent(txtPalabra)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        panGestionarLayout.setVerticalGroup(
            panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGestionarLayout.createSequentialGroup()
                .addGroup(panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGestionarLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPistas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPistas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panPalabras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panPalabras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(25, 25, 112));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("GESTION DE PALABRAS Y PISTAS");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnSalir))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitulo))
                    .addComponent(btnSalir))
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            if (controlador != null) {
                controlador.cerrarSesion();
            } else {
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cerrar sesión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        habilitarPanelGestion(true);
        modoEdicion = true;
        txtPalabra.requestFocus();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
        JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (modoEdicion) {
            actualizarPalabra();
        } else {
            agregarPalabra();
        }
        btnCancelarActionPerformed(null);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCamposGestor();
        habilitarPanelGestion(false);
        resetearModo();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAdmin().setVisible(true);
            }
        });
    }

    private void habilitarPanelGestion(boolean habilitar) {
        panGestionar.setEnabled(habilitar);
        txtPalabra.setEnabled(habilitar);
        txtPistas.setEnabled(habilitar);
        btnGuardar.setEnabled(habilitar);
        btnCancelar.setEnabled(habilitar);

        if (habilitar) {
            panGestionar.setBackground(null);
        } else {
            panGestionar.setBackground(new java.awt.Color(240, 240, 240));
        }
    }

    private void limpiarCampos() {
        txtPalabra.setText("");
        txtPistas.setText("");
    }

    // Métodos consolidados de GestorPalabrasUI
    private void inicializarGestorPalabras() {
        gestorPalabras = new GestorPalabrasXML();
        configurarSeleccion();
    }

    private void configurarSeleccion() {
        tblPalabras.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int filaSeleccionada = tblPalabras.getSelectedRow();
                    if (filaSeleccionada >= 0) {
                        Palabra palabra = modeloTabla.getPalabraAt(filaSeleccionada);
                        txtPalabra.setText(palabra.getPalabra());
                        txtPistas.setText(palabra.getPista());
                    }
                }
            }
        });
    }

    private void cargarDatos() {
        modeloTabla.recargar();
    }

    private boolean validarCampos() {
        if (txtPalabra.getText().trim().isEmpty()) {
            mostrarMensajeError("La palabra no puede estar vacía");
            return false;
        }

        if (txtPistas.getText().trim().isEmpty()) {
            mostrarMensajeError("La pista no puede estar vacía");
            return false;
        }

        return true;
    }

    private void agregarPalabra() {
        if (!validarCampos()) {
            return;
        }

        try {
            gestorPalabras.agregarPalabra(txtPalabra.getText().trim(), txtPistas.getText().trim());
            cargarDatos();
            limpiarCamposGestor();
            mostrarMensajeExito("Palabra agregada exitosamente");
        } catch (Exception e) {
            mostrarMensajeError("Error al agregar la palabra");
        }
    }

    private void actualizarPalabra() {
        if (!modoEdicion || filaSeleccionada < 0) {
            mostrarMensajeError("Debe seleccionar una palabra para actualizar");
            return;
        }

        if (!validarCampos()) {
            return;
        }

        Palabra palabraOriginal = modeloTabla.getPalabraAt(filaSeleccionada);

        if (gestorPalabras.actualizarPalabra(palabraOriginal.getPalabra(), txtPalabra.getText().trim(), txtPistas.getText().trim())) {
            cargarDatos();
            resetearModo();
            mostrarMensajeExito("Palabra actualizada exitosamente");
        } else {
            mostrarMensajeError("Error al actualizar la palabra");
        }
    }

    private void eliminarPalabra() {
        int filaSeleccionada = tblPalabras.getSelectedRow();
        if (filaSeleccionada < 0) {
            mostrarMensajeError("Debe seleccionar una palabra para eliminar");
            return;
        }

        if (confirmarAccion("¿Está seguro de que desea eliminar esta palabra?")) {
            Palabra palabra = modeloTabla.getPalabraAt(filaSeleccionada);

            if (gestorPalabras.eliminarPalabra(palabra.getPalabra())) {
                cargarDatos();
                limpiarCamposGestor();
                resetearModo();
                mostrarMensajeExito("Palabra eliminada exitosamente");
            } else {
                mostrarMensajeError("Error al eliminar la palabra");
            }
        }
    }

    private void limpiarCamposGestor() {
        txtPalabra.setText("");
        txtPistas.setText("");
    }

    private void resetearModo() {
        modoEdicion = false;
        filaSeleccionada = -1;
    }

    // Métodos consolidados de ConfiguradorInterfazAdmin
    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    private boolean confirmarAccion(String mensaje) {
        int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Confirmar", JOptionPane.YES_NO_OPTION);
        return opcion == JOptionPane.YES_OPTION;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPalabras;
    private javax.swing.JLabel lblPistas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panGestionar;
    private javax.swing.JPanel panPalabras;
    private javax.swing.JTable tblPalabras;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextField txtPistas;
    // End of variables declaration//GEN-END:variables
}
