/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficos;

import graficos.figuras.Figura;
import graficos.figuras.Linea;
import graficos.figuras.Palabras;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import logueo_registro.JFLogueo;

/**
 *
 * @author admin
 */
public class JFPizarra extends javax.swing.JFrame {

    private List<Figura> figuras;
    Palabras palabras = new Palabras();
    private String palabraSeleccionada = palabras.obtenerPalabraAleatoria();
    private List<Character> letrasIngresadas = new ArrayList<>();
    private JButton[] btns;
    private int error1;    
    private int error2;
    public String res[];

    /**
     * Creates new form JFPizarra
     */
    public JFPizarra() {
        initComponents();
        inicializarBotones();
        asignarActionListeners();
        ((PanelPizarra) this.panPizarra).setFiguras(new ArrayList<>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPizarra = new PanelPizarra();
        jPanel7 = new javax.swing.JPanel();
        btnB = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnÑ = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtPalabra = new javax.swing.JTextField();
        txtAyuda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Iniciar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPizarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panPizarraLayout = new javax.swing.GroupLayout(panPizarra);
        panPizarra.setLayout(panPizarraLayout);
        panPizarraLayout.setHorizontalGroup(
                panPizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 353, Short.MAX_VALUE)
        );
        panPizarraLayout.setVerticalGroup(
                panPizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TECLADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        btnB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnB.setText("B");
        btnB.setEnabled(false);

        btnA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnA.setText("A");
        btnA.setEnabled(false);

        btnC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnC.setText("C");
        btnC.setEnabled(false);

        btnD.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnD.setText("D");
        btnD.setEnabled(false);

        btnE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnE.setText("E");
        btnE.setEnabled(false);

        btnF.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnF.setText("F");
        btnF.setEnabled(false);

        btnG.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnG.setText("G");
        btnG.setEnabled(false);

        btnH.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnH.setText("H");
        btnH.setEnabled(false);

        btnI.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnI.setText("I");
        btnI.setEnabled(false);

        btnJ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnJ.setText("J");
        btnJ.setEnabled(false);

        btnK.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnK.setText("K");
        btnK.setEnabled(false);

        btnL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnL.setText("L");
        btnL.setEnabled(false);

        btnM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnM.setText("M");
        btnM.setEnabled(false);

        btnN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnN.setText("N");
        btnN.setEnabled(false);

        btnO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnO.setText("O");
        btnO.setEnabled(false);

        btnP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnP.setText("P");
        btnP.setEnabled(false);

        btnQ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnQ.setText("Q");
        btnQ.setEnabled(false);

        btnR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnR.setText("R");
        btnR.setEnabled(false);

        btnS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnS.setText("S");
        btnS.setEnabled(false);

        btnT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnT.setText("T");
        btnT.setEnabled(false);

        btnU.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnU.setText("U");
        btnU.setEnabled(false);

        btnV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnV.setText("V");
        btnV.setEnabled(false);

        btnW.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnW.setText("W");
        btnW.setEnabled(false);

        btnX.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnX.setText("X");
        btnX.setEnabled(false);

        btnY.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnY.setText("Y");
        btnY.setEnabled(false);

        btnZ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnZ.setText("Z");
        btnZ.setEnabled(false);

        btnÑ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnÑ.setText("Ñ");
        btnÑ.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnX, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(btnR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnT, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                                        .addComponent(btnZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btnW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                                        .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                        .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(2, 2, 2)))
                                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnA)
                                        .addComponent(btnB)
                                        .addComponent(btnE)
                                        .addComponent(btnD)
                                        .addComponent(btnC)
                                        .addComponent(btnF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnG)
                                        .addComponent(btnH)
                                        .addComponent(btnK)
                                        .addComponent(btnJ)
                                        .addComponent(btnI)
                                        .addComponent(btnL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnM)
                                        .addComponent(btnN)
                                        .addComponent(btnÑ)
                                        .addComponent(btnO)
                                        .addComponent(btnP)
                                        .addComponent(btnQ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnS)
                                        .addComponent(btnR)
                                        .addComponent(btnT)
                                        .addComponent(btnU)
                                        .addComponent(btnV)
                                        .addComponent(btnW))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnY)
                                        .addComponent(btnZ)
                                        .addComponent(btnX))
                                .addGap(11, 11, 11))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PALABRA OCULTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        txtPalabra.setEditable(false);
        txtPalabra.setBackground(new java.awt.Color(0, 0, 0));
        txtPalabra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPalabra.setForeground(new java.awt.Color(255, 255, 255));
        txtPalabra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAyuda.setBackground(new java.awt.Color(0, 0, 0));
        txtAyuda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtAyuda.setForeground(new java.awt.Color(255, 255, 255));
        txtAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAyudaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Palabra");

        lblAyuda.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAyuda.setText("Ayuda");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAyuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPalabra)
                                        .addComponent(txtAyuda)))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAyuda))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENÚ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        Iniciar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Iniciar.setText("GENERAR PALABRA NUEVA");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        btnIniciar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        help.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        help.setText("INSTRUCCIONES DEL JUEGO");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(help, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Iniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSalir)
                                        .addComponent(btnIniciar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(help)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(panPizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 36, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(panPizarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de querer una palabra nueva?",
                "Ahorcado", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE) == JOptionPane.YES_OPTION) {
            iniciar();
        } else {
            setDefaultCloseOperation(0);
        }

    }//GEN-LAST:event_IniciarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de querer regresar al menú principal?\nSe perderá todo su progreso.",
                "Ahorcado",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            JFLogueo inicio = new JFLogueo();
            inicio.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        JOptionPane.showMessageDialog(null,
                "<html>"
                + "<h2 style='text-align:center;'>🎮 Instrucciones del Ahorcado</h2>"
                + "<p><b>👥 Jugadores:</b> 2 (1 adivinador y 1 moderador)</p>"
                + "<p><b>🎯 Objetivo:</b> Descubrir la palabra o frase incógnita.</p>"
                + "<hr>"
                + "<p><b>📝 Preparación:</b><br>"
                + "- El moderador piensa una palabra o frase secreta.<br>"
                + "- Dibuja una línea por cada letra en una hoja.<br>"
                + "- Se dibuja solo la base de la horca (sin el muñeco).<br>"
                + "- El moderador da una pista al adivinador.</p>"
                + "<hr>"
                + "<p><b>🔁 Turno del jugador:</b><br>"
                + "Puede <b>pedir una letra</b> o <b>adivinar la palabra</b>.</p>"
                + "<p><b>🔤 Pedir una letra:</b><br>"
                + "✔️ Si la letra <b>está</b>: se coloca en la posición correspondiente.<br>"
                + "❌ Si la letra <b>no está</b>: se dibuja una parte del muñeco y se anota la letra usada.</p>"
                + "<p><b>👤 Muñeco:</b><br>"
                + "Se dibuja en 5 partes: cabeza, tronco, brazos y piernas. El adivinador tiene 5 oportunidades de fallar.</p>"
                + "<p><b>💬 Adivinar la palabra:</b><br>"
                + "✔️ Si acierta: 🎉 ¡GANA! El moderador completa la palabra.<br>"
                + "❌ Si falla: se dibuja una parte del muñeco.</p>"
                + "<hr>"
                + "<p><b>🏁 Fin del juego:</b><br>"
                + "🏆 <b>GANA</b> si descubre la palabra o frase secreta.<br>"
                + "💀 <b>PIERDE</b> si se completa el dibujo del muñeco.</p>"
                + "</html>",
                "Ahorcado - Instrucciones", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_helpActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        ((PanelPizarra) this.panPizarra).getFiguras().add(new Linea(50, 50, 100, 10));
        this.panPizarra.repaint();
    }

    private void txtAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAyudaActionPerformed
        if (palabraSeleccionada != null && palabras != null) {
            String pista = palabras.obtenerPista(palabraSeleccionada);
            txtAyuda.setText(pista);
        } else {
            txtAyuda.setText("No hay palabra seleccionada");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPizarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPizarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPizarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPizarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPizarra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JButton btnÑ;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JPanel panPizarra;
    private javax.swing.JTextField txtAyuda;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables

    private List<Character> letrasFallidas = new ArrayList<>();

    private void iniciar() {
        palabraSeleccionada = palabras.obtenerPalabraAleatoria();
        error1 = 0;
        error2 = 6;

        ((PanelPizarra) this.panPizarra).getFiguras().clear();
        //this.panPizarra.repaint();

        txtPalabra.setText("");

        activarTeclado();
        inicializarBotones();

        String palabraActual = palabraSeleccionada.toUpperCase();

        String[] palabrasSeparadas = palabraActual.split(" ");
        int totalLetras = 0;
        for (String palabra : palabrasSeparadas) {
            totalLetras += palabra.length();
        }

        int tamanoTotal = totalLetras + (palabrasSeparadas.length - 1);
        res = new String[tamanoTotal];

        int j = 0;

        for (int k = 0; k < palabrasSeparadas.length; k++) {
            String palabra = palabrasSeparadas[k];
            for (int i = 0; i < palabra.length(); i++) {
                res[j++] = "_";
            }
            if (k < palabrasSeparadas.length - 1) {
                res[j++] = " ";
            }
        }

        actualizarVisualizacionPalabra();
        
        letrasFallidas.clear();

        txtAyuda.setText("");
    }

    private void actualizarLetrasFallidas() {
        txtAyuda.setText("");
        for (JButton btn : btns) {
            if (!btn.isEnabled() && letrasFallidas.contains(btn.getText().charAt(0))) {
                btn.setBackground(java.awt.Color.RED);
            }
        }
    }

    private void inicializarBotones() {
        btns = new JButton[]{
            btnA, btnB, btnC, btnD, btnE,
            btnF, btnG, btnH, btnI, btnJ,
            btnK, btnL, btnM, btnN, btnO,
            btnP, btnQ, btnR, btnS, btnT,
            btnU, btnV, btnW, btnX, btnY, btnZ
        };
    }

    private void asignarActionListeners() {
        // Asignar ActionListener a cada botón
        btnA.addActionListener(e -> procesarLetra('A'));
        btnB.addActionListener(e -> procesarLetra('B'));
        btnC.addActionListener(e -> procesarLetra('C'));
        btnD.addActionListener(e -> procesarLetra('D'));
        btnE.addActionListener(e -> procesarLetra('E'));
        btnF.addActionListener(e -> procesarLetra('F'));
        btnG.addActionListener(e -> procesarLetra('G'));
        btnH.addActionListener(e -> procesarLetra('H'));
        btnI.addActionListener(e -> procesarLetra('I'));
        btnJ.addActionListener(e -> procesarLetra('J'));
        btnK.addActionListener(e -> procesarLetra('K'));
        btnL.addActionListener(e -> procesarLetra('L'));
        btnM.addActionListener(e -> procesarLetra('M'));
        btnN.addActionListener(e -> procesarLetra('N'));
        btnÑ.addActionListener(e -> procesarLetra('Ñ'));
        btnO.addActionListener(e -> procesarLetra('O'));
        btnP.addActionListener(e -> procesarLetra('P'));
        btnQ.addActionListener(e -> procesarLetra('Q'));
        btnR.addActionListener(e -> procesarLetra('R'));
        btnS.addActionListener(e -> procesarLetra('S'));
        btnT.addActionListener(e -> procesarLetra('T'));
        btnU.addActionListener(e -> procesarLetra('U'));
        btnV.addActionListener(e -> procesarLetra('V'));
        btnW.addActionListener(e -> procesarLetra('W'));
        btnX.addActionListener(e -> procesarLetra('X'));
        btnY.addActionListener(e -> procesarLetra('Y'));
        btnZ.addActionListener(e -> procesarLetra('Z'));
    }

    private void activarTeclado() {
        this.btnA.setEnabled(true);
        this.btnB.setEnabled(true);
        this.btnC.setEnabled(true);
        this.btnD.setEnabled(true);
        this.btnE.setEnabled(true);
        this.btnF.setEnabled(true);
        this.btnG.setEnabled(true);
        this.btnH.setEnabled(true);
        this.btnI.setEnabled(true);
        this.btnJ.setEnabled(true);
        this.btnK.setEnabled(true);
        this.btnL.setEnabled(true);
        this.btnM.setEnabled(true);
        this.btnN.setEnabled(true);
        this.btnÑ.setEnabled(true);
        this.btnO.setEnabled(true);
        this.btnP.setEnabled(true);
        this.btnQ.setEnabled(true);
        this.btnR.setEnabled(true);
        this.btnS.setEnabled(true);
        this.btnT.setEnabled(true);
        this.btnU.setEnabled(true);
        this.btnV.setEnabled(true);
        this.btnW.setEnabled(true);
        this.btnX.setEnabled(true);
        this.btnY.setEnabled(true);
        this.btnZ.setEnabled(true);
    }

    /**
     * Procesa la letra seleccionada por el usuario
     *
     * @param letra La letra seleccionada
     */
    private void procesarLetra(char letra) {
        for (JButton btn : btns) {
            if (btn.getText().equals(String.valueOf(letra))) {
                btn.setEnabled(false);
                break;
            }
        }

        boolean letraEncontrada = false;
        String palabraActual = palabraSeleccionada.toUpperCase();

        for (int i = 0; i < palabraActual.length(); i++) {
            if (palabraActual.charAt(i) == letra) {
                letraEncontrada = true;
                int j = 0;
                int posEnRes = 0;

                for (String palabra : palabraActual.split(" ")) {
                    for (int k = 0; k < palabra.length(); k++) {
                        if (j == i) {
                            res[posEnRes] = String.valueOf(letra);
                        }
                        j++;
                        posEnRes++;
                    }
                    if (j < palabraActual.length()) {
                        j++;
                        posEnRes++;
                    }
                }
            }
        }

        actualizarVisualizacionPalabra();
        
        if (!letraEncontrada) {
            error1++;
            letrasFallidas.add(letra);
            //actualizarLetrasFallidas();
            //dibujarAhorcado(error1);

            if (error1 >= error2) {
                JOptionPane.showMessageDialog(this, "¡Has perdido! La palabra era: " + palabraSeleccionada);
                for (JButton btn : btns) {
                    btn.setEnabled(false);
                }
            }
        } else {
            boolean juegoGanado = true;
            for (String s : res) {
                if (s.equals("_")) {
                    juegoGanado = false;
                    break;
                }
            }

            if (juegoGanado) {
                JOptionPane.showMessageDialog(this, "¡Felicidades! Has ganado el juego.");
                for (JButton btn : btns) {
                    btn.setEnabled(false);
                }
            }
        }
    }
    
    private void actualizarVisualizacionPalabra() {
        txtPalabra.setText("");
        for (int i = 0; i < res.length; i++) {
            if (res[i].equals(" ")) {
                txtPalabra.setText(txtPalabra.getText() + "\n");
            } else {
                txtPalabra.setText(txtPalabra.getText() + res[i] + " ");
            }
        }
    }
}
