package logueo_registro;

import controlador.ControladorPrincipal;
import javax.swing.JOptionPane;

public class JFRegistro extends javax.swing.JFrame {

    private ControladorPrincipal controlador;

    public JFRegistro() {
        initComponents();
        configurarVentana();
    }
    
    private void configurarVentana() {
        setTitle("Registro");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    /**
     * Establece el controlador principal
     * @param controlador controlador principal de la aplicación
     */
    public void setControlador(ControladorPrincipal controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPassConfirm = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HANGMAN - REGISTRO");
        setResizable(false);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBackground(new java.awt.Color(218, 182, 126));
        txtUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 300, 40));

        txtPassConfirm.setBackground(new java.awt.Color(218, 182, 126));
        txtPassConfirm.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPassConfirm.setForeground(new java.awt.Color(51, 51, 51));
        txtPassConfirm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.add(txtPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 300, 40));

        txtPass.setBackground(new java.awt.Color(218, 182, 126));
        txtPass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 300, 40));

        btnRegistrar.setBackground(new java.awt.Color(218, 182, 126));
        btnRegistrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(34, 33, 47));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setIconTextGap(0);
        btnRegistrar.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        background.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 140, 50));

        btnVolver.setBackground(new java.awt.Color(172, 77, 45));
        btnVolver.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(233, 206, 161));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        background.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (controlador == null) {
            JOptionPane.showMessageDialog(this, "Error interno: Controlador no inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        controlador.volverAlLogin();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (controlador == null) {
            JOptionPane.showMessageDialog(this, "Error interno: Controlador no inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String nombreUsuario = txtUser.getText().trim();
        String contrasena = new String(txtPass.getPassword());
        String confirmarContrasena = new String(txtPassConfirm.getPassword());
        
        try {
            String error = controlador.procesarRegistro(nombreUsuario, contrasena, confirmarContrasena);
            
            if (error != null) {
                JOptionPane.showMessageDialog(this, error, "Error de Registro", JOptionPane.ERROR_MESSAGE);
                if (error.contains("contraseñas no coinciden")) {
                    txtPassConfirm.setText("");
                    txtPassConfirm.requestFocus();
                } else if (error.contains("usuario ya existe")) {
                    txtUser.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error interno: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassConfirm;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
